#!/usr/bin/env ruby
#
#  Created by cypher on 2007-03-10.
#  Copyright (c) 2007. All rights reserved.
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed one million.

acc = 0

curr = 0
succ = 1

idx = 0
while curr < 1_000_000
  curr, succ = succ, curr + succ
  
  acc += curr if curr % 2 == 0
end

puts acc
