#!/usr/bin/env/ruby

# ----------------------------------------------------------------------
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do
# not exceed four million.
# ----------------------------------------------------------------------

a,b = 1,2
accum = 2
while a+b <= 4_000_000 do
  accum += a+b if ((a+b)%2).zero?
  a,b=b,a+b
end

puts accum
